# Generated by Django 4.1.7 on 2023-02-21 17:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='origem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=255)),
                ('Sobrenome', models.CharField(blank=True, max_length=255)),
                ('Telefone', models.CharField(max_length=255)),
                ('Email', models.CharField(blank=True, max_length=255)),
                ('Data_voo', models.DateTimeField(default=django.utils.timezone.now)),
                ('Ticket_voo', models.CharField(max_length=255)),
                ('Dados_vendedor', models.TextField(blank=True)),
                ('Milheiro', models.CharField(max_length=255)),
                ('Login', models.CharField(max_length=255)),
                ('Senha', models.CharField(max_length=255)),
                ('Cia', models.CharField(max_length=255)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.compania')),
            ],
        ),
    ]
