# Generated by Django 4.1.7 on 2023-02-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_categoria_cliente_compania_remove_cliente_cia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
