# Generated by Django 4.1.7 on 2023-02-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_rename_mostrar_cliente_finalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
