# Generated by Django 4.1.7 on 2023-02-26 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_cliente_foto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='origem',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Origem',
            new_name='Status',
        ),
    ]
