# Generated by Django 4.1.7 on 2023-02-26 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_rename_origem_status_rename_origem_cliente_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='status',
            new_name='origem',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Status',
            new_name='Origem',
        ),
    ]
