# Generated by Django 4.1.7 on 2023-02-26 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_rename_status_origem_rename_status_cliente_origem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='origem',
            new_name='Resultado',
        ),
        migrations.RenameModel(
            old_name='Compania',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Origem',
            new_name='Resultado_orçamento',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Compania',
            new_name='Status_atrelamento',
        ),
    ]
