# Generated by Django 4.1.7 on 2023-02-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_rename_origem_resultado_rename_compania_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Nome',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Chamado',
            field=models.CharField(default=(), max_length=7),
        ),
    ]
