# Generated by Django 4.1.7 on 2023-02-26 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_remove_cliente_nome_cliente_chamado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Data_voo',
            new_name='Data_atrelamento',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Dados_vendedor',
            new_name='Descricao',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Telefone',
        ),
    ]
