# Generated by Django 4.1.7 on 2023-02-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_remove_cliente_login_remove_cliente_milheiro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
