# Generated by Django 4.1.7 on 2023-02-28 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_alter_cliente_descricao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='categoria',
        ),
        migrations.RenameModel(
            old_name='Resultado',
            new_name='modelo',
        ),
    ]
