# Generated by Django 4.1.7 on 2023-02-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_rename_status_categoria_rename_resultado_modelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Status_atrelamento',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Resultado_orçamento',
            new_name='Padrao',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Chamado',
            new_name='Servico',
        ),
    ]
