# Generated by Django 4.1.7 on 2023-02-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_rename_status_atrelamento_cliente_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Servico',
            field=models.CharField(max_length=20),
        ),
    ]
