# Generated by Django 4.1.7 on 2023-02-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0018_alter_cliente_servico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Descricao',
            new_name='Diagnostico',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Data_atrelamento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Orcamento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Preco_ideal',
            field=models.CharField(default='R$', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Preco_max',
            field=models.CharField(default='R$', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Solucao',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
