# Generated by Django 4.1.7 on 2023-03-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_rename_descricao_cliente_diagnostico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Servico',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Solucao',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
