# Generated by Django 4.1.7 on 2023-03-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_alter_cliente_servico_alter_cliente_solucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Fornecedor',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
